version: '2'

services:
  lunchbot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=ecto://kuoGfGzy:y_MiBPcpiDGsR2VHB_@db:5432/lunchbot?ssl=false&pool_size=10"
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - .:/opt/app
      ## uncomment the below lines if you want to see the contents of the
      ## container's deps/ and _build/ directories in your local project,
      ## under container_mix
      # - ./container_mix_artifacts:/opt/mix_artifacts
  
  db:
    image: "postgres:9.6.11"
    environment:
      - POSTGRES_USER=kuoGfGzy
      - POSTGRES_PASSWORD=y_MiBPcpiDGsR2VHB_
    ports:
      - 6543:5432

