version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.1
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_DB: lunchbot_test
          POSTGRES_USER: kuoGfGzy
          POSTGRES_PASSWORD: y_MiBPcpiDGsR2VHB_
    environment:
      MIX_ENV: test
      DATABASE_URL: ecto://kuoGfGzy:y_MiBPcpiDGsR2VHB_@db:5432/lunchbot_test?ssl=false&pool_size=10
    working_directory: ~/lunchbot
    steps:
      - checkout
      - run:
          name: mix local.*
          command: |
            mix local.rebar --force
            mix local.hex --force
      - restore_cache:
          keys:
            - lunchbot-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - save_cache:
          key: lunchbot-{{ checksum "mix.lock" }}
          paths:
            - deps/

      - run: mix format --check-formatted
      - run: mix compile
      - run: mix credo --strict --mute-exit-status
      - run:
          name: mix test (coveralls.circle)
          command: |
            mkdir -p ./test-results/mix
            mix coveralls.circle
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

      - restore_cache:
          keys:
            - lunchbot-plt-
      - run:
          name: restore plts
          command: |
            mkdir -p ./plt
            touch ./plt/files
            mv ./plt/* _build/test/
      - run: mix dialyzer
      - run:
          name: save plts
          command: |
            cp _build/test/*.plt ./plt
            ls ./plt/ > ./plt/files
      - save_cache:
          key: lunchbot-plt-{{ checksum "./plt/files" }}
          paths:
            - ./plt/
